version: "3.3"

networks:
  main-network:
    driver: bridge


services:
  redis:
    image: redis
    ports:
      - '6379:6379'
    networks:
      - main-network
    environment:
      - REDIS_PORT_NUMBER=6379
